In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score

In [43]:
# data collection
wine_dataset = pd.read_csv('WineQT.csv')

In [44]:
#printing the first n rows of the data set
wine_dataset.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4

In [45]:
#getting the statstical measures  of the data set 
wine_dataset.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
count,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000
mean,8.311111,0.531339,0.268364,2.532152,0.086933,15.615486,45.914698,0.996730,3.311015,0.657708,10.442111,5.657043,804.969379
std,1.747595,0.179633,0.196686,1.355917,0.047267,10.250486,32.782130,0.001925,0.156664,0.170399,1.082196,0.805824,463.997116
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000,0.000000
25%,7.100000,0.392500,0.090000,1.900000,0.070000,7.000000,21.000000,0.995570,3.205000,0.550000,9.500000,5.000000,411.000000
50%,7.900000,0.520000,0.250000,2.200000,0.079000,13.000000,37.000000,0.996680,3.310000,0.620000,10.200000,6.000000,794.000000
75%,9.100000,0.640000,0.420000,2.600000,0.090000,21.000000,61.000000,0.997845,3.400000,0.730000,11.100000,6.000000,1209.500000
max,15.900000,1.580000,1.000000,15.500000,0.611000,68.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000,1597.000000

In [46]:
wine_dataset.groupby('quality').mean()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,Id
quality,,,,,,,,,,,,
3,8.450000,0.897500,0.211667,2.666667,0.105333,8.166667,24.500000,0.997682,3.361667,0.550000,9.691667,1121.166667
4,7.809091,0.700000,0.165758,2.566667,0.094788,14.848485,40.606061,0.996669,3.391212,0.637879,10.260606,692.848485
5,8.161077,0.585280,0.240124,2.540476,0.091770,16.612836,55.299172,0.997073,3.302091,0.613375,9.902277,753.925466
6,8.317749,0.504957,0.263680,2.444805,0.085281,15.215368,39.941558,0.996610,3.323788,0.676537,10.655339,854.625541
7,8.851049,0.393671,0.386573,2.760140,0.075217,14.538462,37.489510,0.996071,3.287133,0.743566,11.482634,830.349650
8,8.806250,0.410000,0.432500,2.643750,0.070187,11.062500,29.375000,0.995553,3.240625,0.766250,11.937500,797.875000

In [47]:
#observations when wine quality is good volatile acidity is less and when its bad volitile acidity is more
x = wine_dataset.drop('quality', axis=1)
print(x)

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076
1               7.8             0.880         0.00             2.6      0.098
2               7.8             0.760         0.04             2.3      0.092
3              11.2             0.280         0.56             1.9      0.075
4               7.4             0.700         0.00             1.9      0.076
...             ...               ...          ...             ...        ...
1138            6.3             0.510         0.13             2.3      0.076
1139            6.8             0.620         0.08             1.9      0.068
1140            6.2             0.600         0.08             2.0      0.090
1141            5.9             0.550         0.10             2.2      0.062
1142            5.9             0.645         0.12             2.0      0.075

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56
1                    25.0                  67.0  0.99680  3.20       0.68
2                    15.0                  54.0  0.99700  3.26       0.65
3                    17.0                  60.0  0.99800  3.16       0.58
4                    11.0                  34.0  0.99780  3.51       0.56
...                   ...                   ...      ...   ...        ...
1138                 29.0                  40.0  0.99574  3.42       0.75
1139                 28.0                  38.0  0.99651  3.42       0.82
1140                 32.0                  44.0  0.99490  3.45       0.58
1141                 39.0                  51.0  0.99512  3.52       0.76
1142                 32.0                  44.0  0.99547  3.57       0.71

      alcohol    Id
0         9.4     0
1         9.8     1
2         9.8     2
3         9.8     3
4         9.4     4
...       ...   ...
1138     11.0  1592
1139      9.5  1593
1140     10.5  1594
1141     11.2  1595
1142     10.2  1597

[1143 rows x 12 columns]

In [48]:
y= wine_dataset['quality']
print(y)

0       5
1       5
2       5
3       6
4       5
       ..
1138    6
1139    6
1140    5
1141    6
1142    5
Name: quality, Length: 1143, dtype: int64

In [49]:
#label binirization
#now we will have value as zero or one 1 if it is>=7 or else 0
y = wine_dataset['quality'].apply(lambda y_value: 1 if y_value>=7 else 0)
print(y)

0       0
1       0
2       0
3       0
4       0
       ..
1138    0
1139    0
1140    0
1141    0
1142    0
Name: quality, Length: 1143, dtype: int64

In [51]:
#splitting the data into train and test 
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size=0.2, stratify=y,random_state=2)

In [52]:
print(x.shape, x_train.shape , x_test.shape)

(1143, 12) (914, 12) (229, 12)

In [53]:
# model training using random forest classifier
model = RandomForestClassifier()

In [54]:
model.fit(x_train, y_train)

RandomForestClassifier()

In [56]:

x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction,y_test)
print(test_data_accuracy)

0.8820960698689956

In [57]:
fixed_acidity = int(input('Pleasse enter the fixed acidity value:-  '))
volatile_acidity = int(input('Pleasse enter the volatile acidity value :-  '))
cetric_acid = int(input('Pleasse enter the cetric acid value :-  '))
resudial_sugar= int(input('Pleasse enter the  resudial sugar value:-  '))
chlorides= int(input('Pleasse enter the chlorids value:-  '))

free_sulfur_dioxide  = int(input('Pleasse enter the free sulfur dioxide value:-  '))
total_sulfur_dioxide = int(input('Pleasse enter the total sufur dioxide value :-  '))
density = int(input('Pleasse enter the density value :-  '))
ph= int(input('Pleasse enter the  ph value:-  '))
sulphates= int(input('Pleasse enter the sulphates  value:-  '))
alcohol= int(input('Pleasse enter the  alcohol value:-  '))
id= int(input('Pleasse enter the id value:-  '))

ValueError: invalid literal for int() with base 10: ''

In [ ]:
input_data = (fixed_acidity,volatile_acidity,cetric_acid,resudial_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,id)
# changing input data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshaping the array as we are predicting it for only one instance
input_data_reshape = input_data_as_numpy_array.reshape(1,-1)

#standardize the input data
std_data = scaler.transform(input_data_reshape)
print( std_data)

prediction = classifer.predict(std_data)
print(prediction)

if (prediction [0]==0):
    print('The wine is not of good quality')
    engine.say('the wine is not of good quality')
    engine.runAndWait()
else:
    print('The wine is of good quality')
    engine.say('the wine is of good quality')
    engine.runAndWait()